openapi: 3.0.1
info:
    title: Example API
    description: This is an example API
    version: 1.0.0
servers:
    - url: http://example.com
      description: Example URL
paths:
    /greeting:
        get: 
            tags: [Endpoints]
            description: Retrieves an greeting
            operationId: getGreeting
            responses:
                '200': 
                    description: Responds with a greeting
                    content: 
                        application/json:
                            schema: 
                                $ref: schemas/get-greeting/response/200.json
                            examples:
                                default:
                                    description: Successfull response
                                    value:
                                        $ref: examples/get-greeting/response/200/default.json
                                alternate:
                                    description: Alternate successfull response
                                    value:
                                        $ref: examples/get-greeting/response/200/alternate.json
